apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: vishvajitcloud/vishvaops_store:home-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
