apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-googlegrocery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishvajit-cloud/kubernetes-vishvaops-ecommerce-microservices-app.git
    path: frontend/googlegrocery
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
