apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: vishvajitcloud/vishvaops_store:googlemusic-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlemusic-service
  labels:
    app: googlemusic
spec:
  type: ClusterIP
  selector:
    app: googlemusic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
