apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobiles-deployment
  labels:
    app: mobiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobiles
  template:
    metadata:
      labels:
        app: mobiles
    spec:
      containers:
      - name: mobiles
        image: vishvajitcloud/vishvaops_store:mobiles-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
  labels:
    app: mobiles
spec:
  type: ClusterIP
  selector:
    app: mobiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
