apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: vishvajitcloud/vishvaops_store:googlepay-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlepay-service
  labels:
    app: googlepay
spec:
  type: ClusterIP
  selector:
    app: googlepay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
