apiVersion: apps/v1
kind: Deployment
metadata:
  name: beauty-deployment
  labels:
    app: beauty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      labels:
        app: beauty
    spec:
      containers:
      - name: beauty
        image: vishvajitcloud/vishvaops_store:beauty-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beauty-service
  labels:
    app: beauty
spec:
  type: ClusterIP
  selector:
    app: beauty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
