apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-deployment
  labels:
    app: fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion
  template:
    metadata:
      labels:
        app: fashion
    spec:
      containers:
      - name: fashion
        image: vishvajitcloud/vishvaops_store:fashion-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  labels:
    app: fashion
spec:
  type: ClusterIP
  selector:
    app: fashion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
