apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: vishvajitcloud/vishvaops_store:books-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
