apiVersion: apps/v1
kind: Deployment
metadata:
  name: toys-deployment
  labels:
    app: toys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toys
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - name: toys
        image: vishvajitcloud/vishvaops_store:toys-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: toys-service
  labels:
    app: toys
spec:
  type: ClusterIP
  selector:
    app: toys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
