apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: vishvajitcloud/vishvaops_store:googlegrocery-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlegrocery-service
  labels:
    app: googlegrocery
spec:
  type: ClusterIP
  selector:
    app: googlegrocery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
