apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-wheelers-deployment
  labels:
    app: two-wheelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-wheelers
  template:
    metadata:
      labels:
        app: two-wheelers
    spec:
      containers:
      - name: two-wheelers
        image: vishvajitcloud/vishvaops_store:two-wheelers-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: two-wheelers-service
  labels:
    app: two-wheelers
spec:
  type: ClusterIP
  selector:
    app: two-wheelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
